version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: laravel-test:0.5
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4001:80"
    networks:
      - webnet
networks:
  webnet:
