version: "3"
services:
  web:
    image: alpine-web:0.3
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  api:
    image: alpine-api:0.1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4001:80"
    networks:
      - webnet
  mysql:
    image: mysql:5.7
    volumes:
       - /Users/adminmwc/dev/home/www/docker-data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - webnet
networks:
  webnet:
