version: "3"
services:
  web:
    image: laravel-web:dev
    volumes:
       - /Users/adminmwc/dev/home/www/aws_laravel_test:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  api:
    image: laravel-api:dev
    volumes:
       - /Users/adminmwc/dev/home/www/aws_laravel_test_api:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4001:80"
    networks:
      - webnet
    dns: 8.8.8.8
  mysql:
    image: mysql:5.7
    volumes:
       - /Users/adminmwc/dev/home/www/docker-data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
    networks:
      - webnet
networks:
  webnet:
