FROM ulsmith/alpine-apache-php7
 
RUN apk add --no-cache mysql-client

#COPY ./ /app
#RUN chown -R apache:apache  /app/storage

ENV API_URL=http://api
ENV OAUTH_CLIENT_ID=2
ENV OAUTH_CLIENT_SECRET=GzrJTDlKZQCAAKzP6ruJsVtRlnyFFFnXXgkBu8la
