version: "3"
services:
  web:
    image: blueminboy/laravel-web:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  api:
    image: blueminboy/laravel-api:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4001:80"
    networks:
      - webnet
    dns: 8.8.8.8
networks:
  webnet:
